azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: public
  type: manual
  subnets:
  - range: 10.244.0.0/17
    gateway: 10.244.0.1
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: []
    cloud_properties:
      name: random
- name: private
  type: manual
  subnets:
  - range: 10.244.128.0/17
    gateway: 10.244.128.1
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: []
    cloud_properties:
      name: random

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: public
